apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-skatteetaten-api
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nais.io/restricted: "true"

spec:
  image: {{ image }}
  port: 8096
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: false
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2048Mi
      cpu: "1"
    requests:
      memory: 1024Mi
      cpu: 200m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ba-skatteetaten-api.dev.adeo.no
    - https://familie-ba-skatteetaten-api.dev.intern.nav.no
    - https://familie-ba-skatteetaten-api.dev-fss-pub.nais.io
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
    - name: JAVA_OPTS
      value: "-Xmx1g"
