name: Build-Deploy-Preprod
on:
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:
env:
  IMAGE: ghcr.io/navikt/familie-ba-skatteetaten-api:${{ github.sha }}
jobs:
  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Kjør ktlint
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn antrun:run@ktlint
  deploy:
    name: Bygg app/image, push til github, deploy til dev-fss/prod-fss
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml
      - name: Publish Test Report
        if: ${{ failure() }}
        uses: scacap/action-surefire-report@v1.6.1
      - name: Login to GitHub Container Registry
        if: github.triggering_actor != 'dependabot[bot]'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        if: github.triggering_actor != 'dependabot[bot]'
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE
      - name: Deploy til dev-gcp
        if: github.triggering_actor != 'dependabot[bot]'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais-preprod.yaml
