name: Build-Deploy-Prod
on:
  push:
    branches:
      - 'main'
env:
  IMAGE: ghcr.io/navikt/familie-ba-skatteetaten-api:${{ github.sha }}
  IMAGE_LATEST: ghcr.io/navikt/familie-ba-skatteetaten-api:latest
jobs:
  deploy:
    name: Bygg app/image, push til github, deploy til dev-fss/prod-fss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml
      - name: Publish Test Report
        if: ${{ failure() }}
        uses: scacap/action-surefire-report@v1.0.13
      - name: Login to GitHub Container Registry
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ${IMAGE} -t ${IMAGE_LATEST} .
          docker push ${IMAGE}
          docker push ${IMAGE_LATEST}
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais-preprod.yaml
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais-prod.yaml
